Tutorial Part 1
neighborhoods/phpunit-first-steps pull request #3
Opened 2018-12-21 21:32 UTC by harshpatel991

**Should be merged after add-docker.**

2018-12-22 11:11 UTC, timrourke requested changes

2018-12-22 11:11 UTC, timrourke commented on tests/UsernameTest.php
> +
potential blocker: in the interest of communicating best practices it would probably be good to use `declare(strict_types=1);` here

2018-12-22 11:11 UTC, timrourke commented on phpunit.xml
> +         beStrictAboutCoversAnnotation="true"
non-blocking question: the `forceCoversAnnotation` and `beStrictAboutCoversAnnotation` might not be necessary. what do you think? they can improve the quality of coverage reporting (eg. incidentally executed code that a parent method calls won't count toward coverage reporting totals) but may be a bit of a hindrance getting things rolling to start with, explaining that context about what the `@covers` annotations do for the first tests in the tutorial would be a heavy burden for a first-time tester

2018-12-29 20:28 UTC, harshpatel991 commented on phpunit.xml
> +         beStrictAboutCoversAnnotation="true"
I agree that these would probably be too much for a first time tutorial. Though, these options are included as part of the default generated `phpunit.xml` file. I don't know if we need to go out of our way to say something like "now remove these two lines"

2018-12-29 20:28 UTC, harshpatel991 commented on tests/UsernameTest.php
> +
Fixed

2019-01-02 19:45 UTC, timrourke approved these changes

2019-01-22 17:07 UTC, merged